file:C:/Program Files/Git/etc/gitconfig	diff.astextplain.textconv=astextplain
file:C:/Program Files/Git/etc/gitconfig	filter.lfs.clean=git-lfs clean -- %f
file:C:/Program Files/Git/etc/gitconfig	filter.lfs.smudge=git-lfs smudge -- %f
file:C:/Program Files/Git/etc/gitconfig	filter.lfs.process=git-lfs filter-process
file:C:/Program Files/Git/etc/gitconfig	filter.lfs.required=true
file:C:/Program Files/Git/etc/gitconfig	http.sslbackend=schannel
file:C:/Program Files/Git/etc/gitconfig	core.autocrlf=true
file:C:/Program Files/Git/etc/gitconfig	core.fscache=true
file:C:/Program Files/Git/etc/gitconfig	core.symlinks=false
file:C:/Program Files/Git/etc/gitconfig	pull.rebase=false
file:C:/Program Files/Git/etc/gitconfig	credential.helper=manager
file:C:/Program Files/Git/etc/gitconfig	credential.https://dev.azure.com.usehttppath=true
file:C:/Program Files/Git/etc/gitconfig	init.defaultbranch=master
file:C:/Users/Usman Ghani/.gitconfig	user.name=Usman
file:C:/Users/Usman Ghani/.gitconfig	user.email=m.usman.4.work@gmail.com
file:C:/Users/Usman Ghani/.gitconfig	filter.lfs.process=git-lfs filter-process
file:C:/Users/Usman Ghani/.gitconfig	filter.lfs.required=true
file:C:/Users/Usman Ghani/.gitconfig	filter.lfs.clean=git-lfs clean -- %f
file:C:/Users/Usman Ghani/.gitconfig	filter.lfs.smudge=git-lfs smudge -- %f
file:.git/config	core.repositoryformatversion=0
file:.git/config	core.filemode=false
file:.git/config	core.bare=false
file:.git/config	core.logallrefupdates=true
file:.git/config	core.symlinks=false
file:.git/config	core.ignorecase=true
file:.git/config	remote.origin.url=https://github.com/gunee-exe/whispr
file:.git/config	remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
