// ⚠️ PLACEHOLDER FILE — DO NOT USE AS-IS ⚠️
//
// This file is normally auto-generated by running:
//   flutterfire configure
// from your project root, after you've created a Firebase project in the
// console and run `firebase login`. That command overwrites this file with
// real apiKey/appId/projectId values for each platform you select.
//
// I'm leaving this here as a structural placeholder so main.dart compiles
// conceptually and so you know exactly what shape the real file takes —
// but you MUST run `flutterfire configure` yourself and let it replace
// this file before the app can actually reach your Cloud Function.
//
// Steps (run from your project root, in your own terminal):
//   1. npm install -g firebase-tools   (if you don't have it)
//   2. dart pub global activate flutterfire_cli
//   3. firebase login
//   4. flutterfire configure
//      → pick/create your Firebase project
//      → select iOS + Android (+ web if you want it)
//   This regenerates this exact file with real values.

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web — '
        'run flutterfire configure and select web if you need it.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ⚠️ Replace via `flutterfire configure` — these are placeholders only.

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAERdgqWaReBPO6YwOipsBq3a_KqXI_nzM',
    appId: '1:639389107798:android:47fbf170893f61f2d09df7',
    messagingSenderId: '639389107798',
    projectId: 'whispr-app1',
    storageBucket: 'whispr-app1.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcLDD914elumhReMvlkImNUbG95Onckac',
    appId: '1:639389107798:ios:7bebdbce71dcf15bd09df7',
    messagingSenderId: '639389107798',
    projectId: 'whispr-app1',
    storageBucket: 'whispr-app1.firebasestorage.app',
    iosBundleId: 'com.example.whispr',
  );
}
